### ISSUE TITLE
Incompatiable with IPv6 address??  1.18.2

### ISSUE THREAD

**Issue by HandsomeYDZ** [DaDerpDuck/Seamless-Loading-Screen-Forge#20]
When my friend tried to access the server using an ipv6 address, the game crashed.
![32b384ec01acc8765973da37688cb82c](https://github.com/DaDerpDuck/Seamless-Loading-Screen-Forge/assets/124165820/05fd88b0-1897-4b77-9b2b-5e3232d84e98)

**Comment by DaDerpDuck** [comment]
This was an issue I fixed in the 1.19 version, caused by me forgetting to sanitize the file name. I'll back port the fix later today or tomorrow.

**Comment by HandsomeYDZ** [comment]
thanks~!
