### ISSUE TITLE
[1.18.2] Joining multiplayer via IPv6 and/or IPv4 with port causes crash due to invalid character ":" in filename

### ISSUE THREAD

**Issue by KxttyKxt** [DaDerpDuck/Seamless-Loading-Screen-Forge#22]
This mod takes a screenshot of the last frame of the world and names it according to the world's filename. When connecting to a multiplayer game via IP that contains a colon either because it's IPv6 or because a port is specified, the game crashes. This is because the mod calls a file whose name contains the invalid character ":" because the screenshot was named after the IP.

**Comment by DaDerpDuck** [comment]
This has been fixed with the latest push to 1.18. If you're still facing issues, message me here.
