### ISSUE TITLE
Performance bug

### ISSUE THREAD

**Issue by Rosentti** [DaDerpDuck/Seamless-Loading-Screen-Forge#3]
With this mod, and only this mod enabled, I get spikes in alt+f3 mode, and when walking.
This seems to happen roughly every 1 second, and is in sync with disk access. 
Edit: The file it is trying to open is
`./saves/New World (2)/icon.png`
Edit 2: It is the icon auto-update feature. Maybe it should run async, or after exiting the game?

![image](https://user-images.githubusercontent.com/32398752/122042148-738f3480-cde2-11eb-9c5a-0b249b7428bf.png)

**Comment by DaDerpDuck** [comment]
You are right, it is coming as an effect of the icon auto-update feature. Currently, I'm using a mixin to tell Minecraft that an icon of the world hasn't been set, forcing it to take make a new icon once in a while. I'll see if I could get it to be saved async instead

**Comment by DaDerpDuck** [comment]
That wasn't trivial so I'm just gonna have it save on exit instead
